// frontend-react/src/components/Sidebar.tsx
import { NavLink } from 'react-router-dom'
import {
  Inbox,
  FolderKanban,
  Clock,
  Tag,
  Calendar,
  FileText,
  Trash2,
  Timer,
  Home,
  Lightbulb,
  Trophy,
  Puzzle,
  Heart,
  Library,
  Moon,
  Network
} from 'lucide-react'
import { cn } from '@/lib/utils'

const menuGroups = [
  {
    title: 'GTD 时间管理',
    items: [
      { path: '/inbox', label: '收集箱', icon: Inbox },
      { path: '/projects', label: '项目清单', icon: FolderKanban },
      { path: '/next-actions', label: '下一步行动', icon: Tag },
      { path: '/waiting', label: '等待清单', icon: Clock },
      { path: '/someday', label: '可能清单', icon: Calendar },
      { path: '/reference', label: '参考资料', icon: FileText },
      { path: '/trash', label: '回收箱', icon: Trash2 },
      { path: '/calendar', label: '日历', icon: Calendar },
      { path: '/pomodoro', label: '番茄钟', icon: Timer },
      { path: '/mindmap', label: '思维导图', icon: Network },
    ],
  },
  {
    title: '锚点 成长陪伴',
    items: [
      { path: '/anchor', label: '灵感捕捉', icon: Home },
      { path: '/inspirations', label: '灵感信箱', icon: Lightbulb },
      { path: '/achievements', label: '成果箱', icon: Trophy },
      { path: '/skills', label: '技能拼图', icon: Puzzle },
      { path: '/emotion', label: '情绪树洞', icon: Heart },
      { path: '/materials', label: '投喂库', icon: Library },
      { path: '/bedtime', label: '睡前仪式', icon: Moon },
    ],
  },
]

interface SidebarProps {
  isOpen: boolean
  onClose: () => void
}

export function Sidebar({ isOpen, onClose }: SidebarProps) {
  return (
    <>
      {isOpen && (
        <div
          className="fixed inset-0 z-40 bg-black/50 md:hidden"
          onClick={onClose}
        />
      )}
      <aside
        className={cn(
          'fixed inset-y-0 left-0 z-50 w-56 bg-white border-r border-gray-200 transform transition-transform duration-200 ease-in-out md:translate-x-0',
          isOpen ? 'translate-x-0' : '-translate-x-full'
        )}
      >
        <div className="flex flex-col h-full">
          <div className="p-4 border-b border-gray-200">
            <h1 className="text-xl font-bold text-primary">GTD + 锚点</h1>
          </div>
          <nav className="flex-1 overflow-y-auto py-4">
            {menuGroups.map((group) => (
              <div key={group.title} className="mb-4">
                <div className="px-4 py-2 text-xs font-semibold text-gray-400 uppercase tracking-wider">
                  {group.title}
                </div>
                <ul>
                  {group.items.map((item) => (
                    <li key={item.path}>
                      <NavLink
                        to={item.path}
                        onClick={onClose}
                        className={({ isActive }) =>
                          cn(
                            'flex items-center gap-3 px-4 py-2.5 text-sm transition-colors',
                            isActive
                              ? 'bg-primary/10 text-primary border-r-2 border-primary'
                              : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'
                          )
                        }
                      >
                        <item.icon className="h-4 w-4" />
                        {item.label}
                      </NavLink>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </nav>
        </div>
      </aside>
    </>
  )
}

// frontend/src/components/Sidebar.vue
<template>
  <el-menu
    :default-active="currentPath"
    class="sidebar-menu"
    router
  >
    <div class="logo">
      <h2>锚点</h2>
      <span class="subtitle">高敏感+ADHD+INFP 专属</span>
    </div>

    <!-- 锚点模块 -->
    <div class="menu-group">
      <div class="menu-group-title">成长陪伴</div>
      <el-menu-item index="/anchor">
        <el-icon><EditPen /></el-icon>
        <span>灵感捕捉</span>
      </el-menu-item>
      <el-menu-item index="/inspirations">
        <el-icon><MessageBox /></el-icon>
        <span>灵感信箱</span>
      </el-menu-item>
      <el-menu-item index="/achievements">
        <el-icon><Collection /></el-icon>
        <span>成果收集箱</span>
      </el-menu-item>
      <el-menu-item index="/skills">
        <el-icon><PieChart /></el-icon>
        <span>技能拼图</span>
      </el-menu-item>
      <el-menu-item index="/emotion">
        <el-icon><ChatDotRound /></el-icon>
        <span>情绪树洞</span>
      </el-menu-item>
      <el-menu-item index="/materials">
        <el-icon><FolderOpened /></el-icon>
        <span>投喂库</span>
      </el-menu-item>
      <el-menu-item index="/bedtime">
        <el-icon><Sunny /></el-icon>
        <span>睡前小台灯</span>
      </el-menu-item>
    </div>

    <el-divider />

    <!-- GTD模块 -->
    <div class="menu-group">
      <div class="menu-group-title">时间管理</div>
      <el-menu-item index="/gtd/inbox">
        <el-icon><Box /></el-icon>
        <span>收集箱</span>
      </el-menu-item>
      <el-menu-item index="/gtd/projects">
        <el-icon><Folder /></el-icon>
        <span>项目清单</span>
      </el-menu-item>
      <el-menu-item index="/gtd/waiting">
        <el-icon><Clock /></el-icon>
        <span>等待清单</span>
      </el-menu-item>
      <el-menu-item index="/gtd/context">
        <el-icon><Check /></el-icon>
        <span>执行清单</span>
      </el-menu-item>
      <el-menu-item index="/gtd/someday">
        <el-icon><Star /></el-icon>
        <span>可能清单</span>
      </el-menu-item>
      <el-menu-item index="/gtd/quadrants">
        <el-icon><Grid /></el-icon>
        <span>四象限</span>
      </el-menu-item>
      <el-menu-item index="/gtd/pomodoro">
        <el-icon><Timer /></el-icon>
        <span>番茄钟</span>
      </el-menu-item>
    </div>
  </el-menu>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { EditPen, MessageBox, Collection, PieChart, ChatDotRound, FolderOpened, Sunny, Box, Folder, Clock, Check, Star, Grid, Timer } from '@element-plus/icons-vue'

const route = useRoute()
const currentPath = computed(() => route.path)
</script>

<style scoped>
.sidebar-menu {
  height: 100vh;
  border-right: 1px solid #e0e0e0;
  overflow-y: auto;
}

.logo {
  padding: 20px;
  text-align: center;
  border-bottom: 1px solid #eee;
}

.logo h2 {
  margin: 0;
  color: #008080;
}

.logo .subtitle {
  font-size: 12px;
  color: #999;
}

.menu-group {
  padding: 10px 0;
}

.menu-group-title {
  padding: 8px 20px;
  font-size: 12px;
  color: #999;
  text-transform: uppercase;
}

.el-menu-item {
  display: flex;
  align-items: center;
  gap: 8px;
  height: 44px;
}

.el-divider {
  margin: 5px 0;
}
</style>
