// frontend/src/views/anchor/MaterialLib.vue
<template>
  <div class="material-lib">
    <h2>灵感投喂库</h2>

    <!-- 添加素材 -->
    <div class="add-form">
      <el-input v-model="newTitle" placeholder="素材标题" style="width: 200px; margin-right: 10px;" />
      <el-input v-model="newUrl" placeholder="素材链接（可选）" style="width: 300px; margin-right: 10px;" />
      <el-button type="primary" @click="handleSave">添加素材</el-button>
    </div>

    <!-- 素材列表 -->
    <div class="material-list">
      <el-card v-for="item in materials" :key="item.id" class="material-card" shadow="hover">
        <div class="material-title">{{ item.title || '无标题' }}</div>
        <div v-if="item.url" class="material-url">
          <a :href="item.url" target="_blank">{{ item.url }}</a>
        </div>
        <div class="card-footer">
          <span class="time">{{ formatTime(item.createTime) }}</span>
          <el-button size="small" type="danger" @click="handleDelete(item.id)">删除</el-button>
        </div>
      </el-card>
      <el-empty v-if="!materials.length" description="投喂库是空的，去找点有趣的内容吧" />
    </div>

    <!-- 温柔提示 -->
    <div class="gentle-tip">
      没关系哦，灵感有时候需要睡一觉才会冒出来，先去做个5分钟的微动作，或者去情绪树洞说说话吧
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useAnchorStore } from '../../stores/anchorStore'
import { ElMessage } from 'element-plus'

const store = useAnchorStore()

const newTitle = ref('')
const newUrl = ref('')

const materials = computed(() => store.materials)

const handleSave = async () => {
  if (!newTitle.value.trim() && !newUrl.value.trim()) return

  await store.saveMaterial({
    title: newTitle.value.trim() || null,
    url: newUrl.value.trim() || null
  })

  newTitle.value = ''
  newUrl.value = ''
  ElMessage.success('素材已添加')
}

const handleDelete = async (id: number) => {
  await store.deleteMaterial(id)
  ElMessage.success('已删除')
}

const formatTime = (time: string) => {
  if (!time) return ''
  return new Date(time).toLocaleString('zh-CN', { month: 'numeric', day: 'numeric' })
}

onMounted(() => {
  store.fetchMaterials()
})
</script>

<style scoped>
.material-lib {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

.add-form {
  background: white;
  border-radius: 12px;
  padding: 20px;
  margin-bottom: 20px;
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 10px;
}

.material-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 15px;
}

.material-card {
  margin-bottom: 0;
}

.material-title {
  font-weight: 500;
  margin-bottom: 8px;
}

.material-url {
  margin-bottom: 10px;
}

.material-url a {
  color: #409eff;
  font-size: 12px;
  text-decoration: none;
}

.material-url a:hover {
  text-decoration: underline;
}

.card-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.time {
  font-size: 12px;
  color: #999;
}

.gentle-tip {
  text-align: center;
  color: #999;
  font-size: 14px;
  margin-top: 30px;
  padding: 15px;
  background: #f5f7fa;
  border-radius: 8px;
}
</style>

// frontend-react/src/pages/anchor/MaterialLib.tsx
import { useState, useEffect } from 'react'
import { Plus, Trash2, ExternalLink } from 'lucide-react'
import { useAnchorStore } from '@/store/anchorStore'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent } from '@/components/ui/card'
import { ScrollArea } from '@/components/ui/scroll-area'

export function MaterialLib() {
  const { materials, fetchMaterials, createMaterial, deleteMaterial } = useAnchorStore()
  const [newTitle, setNewTitle] = useState('')
  const [newUrl, setNewUrl] = useState('')
  const [newContent, setNewContent] = useState('')

  useEffect(() => {
    fetchMaterials()
  }, [])

  const handleAdd = async () => {
    if (!newTitle.trim()) return
    await createMaterial({
      title: newTitle.trim(),
      url: newUrl.trim(),
      content: newContent.trim(),
    })
    setNewTitle('')
    setNewUrl('')
    setNewContent('')
  }

  const handleDelete = async (id: number) => {
    await deleteMaterial(id)
  }

  return (
    <div className="max-w-4xl mx-auto">
      <h2 className="text-2xl font-bold mb-2">灵感投喂库</h2>
      <p className="text-gray-500 mb-6">收藏对你有启发的文章、视频、素材</p>

      <Card className="mb-6">
        <CardContent className="p-4 space-y-3">
          <Input
            value={newTitle}
            onChange={(e) => setNewTitle(e.target.value)}
            placeholder="素材标题"
          />
          <Input
            value={newUrl}
            onChange={(e) => setNewUrl(e.target.value)}
            placeholder="素材链接 (可选)"
          />
          <Input
            value={newContent}
            onChange={(e) => setNewContent(e.target.value)}
            placeholder="简要说明 (可选)"
          />
          <Button onClick={handleAdd} className="w-full">
            <Plus className="h-4 w-4 mr-2" />
            添加素材
          </Button>
        </CardContent>
      </Card>

      <ScrollArea className="h-[calc(100vh-380px)]">
        <div className="grid md:grid-cols-2 gap-4">
          {materials.map((item) => (
            <Card key={item.id}>
              <CardContent className="p-4">
                <div className="flex items-start gap-3">
                  <div className="flex-1 min-w-0">
                    <h4 className="font-medium text-sm truncate">{item.title}</h4>
                    {item.content && (
                      <p className="text-xs text-gray-500 mt-1 line-clamp-2">{item.content}</p>
                    )}
                    {item.url && (
                      <a
                        href={item.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-primary hover:underline flex items-center gap-1 mt-2"
                      >
                        <ExternalLink className="h-3 w-3" />
                        查看链接
                      </a>
                    )}
                  </div>
                  <Button
                    size="icon"
                    variant="ghost"
                    className="h-6 w-6 text-gray-400 hover:text-red-500 flex-shrink-0"
                    onClick={() => item.id && handleDelete(item.id)}
                  >
                    <Trash2 className="h-3 w-3" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
          {materials.length === 0 && (
            <div className="col-span-2 text-center py-12 text-gray-400">
              投喂库是空的
            </div>
          )}
        </div>
      </ScrollArea>
    </div>
  )
}
